
var perfil = angular.module('perfil', ['ngRoute', 'ngResource', 'controllers']);

justdoit.config([
  '$routeProvider', function($routeProvider) {
    return $routeProvider.when('/', {
      templateUrl: "index.html",
      controller: 'TasksController'
    }).when('/tasks/new', {
      templateUrl: "form.html",
      controller: 'TaskController'
    }).when('/tasks/:taskId', {
      templateUrl: "show.html",
      controller: 'TaskController'
    }).when('/tasks/:taskId/edit', {
      templateUrl: "form.html",
      controller: 'TaskController'
    }).when('/subtasks/new', {
      templateUrl: "form.html",
      controller: 'SubtaskController'
    }).when('/subtasks/:subtaskId', {
      templateUrl: "show.html",
      controller: 'SubtaskController'
    }).when('/subtasks/:subtaskId/edit', {
      templateUrl: "form.html",
      controller: 'SubtaskController'
    });
  }
]);

myapp.config([
  '$routeProvider', function($routeProvider) {
    return $routeProvider.when('/', {
      templateUrl: "index.html",
      controller: 'FeedController'
    }).when(':perfilId/perfil/', {
      templateUrl: "perfil.html",
      controller: 'SubtaskController'
    });
  }
]);

// ---
// generated by coffee-script 1.9.2
